-- What are the earliest and latest dates crimes were reported in the result set (this requires MIN() and MAX() functions)

SELECT MIN(DATE.DATE_REPORTED) AS 'Earlist Report', MAX(DATE.DATE_REPORTED) AS 'Most Recent Report'
FROM DATE;

-- What are the earliest and latest dates crimes occurred in the result set (this requires MIN() and MAX() functions)?

SELECT MIN(DATE_OCCURRED) AS 'Earlist Occurrence', MAX(DATE_OCCURRED) AS 'Most Recent Occurrence'
FROM DATE;

-- What are the 5 most frequent crimes across the dataset and their volumes?

SELECT CRIME.OFFENSE_CLASSIFICATION, COUNT(*)
FROM CRIME
GROUP BY CRIME.OFFENSE_CLASSIFICATION
ORDER BY COUNT(*) DESC
LIMIT 5;

-- What 10 zip codes report the most crime and what are their volumes?

 SELECT LOCATION.ZIP_CODE, COUNT(*)
FROM LOCATION
GROUP BY LOCATION.ZIP_CODE
ORDER BY COUNT(*) DESC
LIMIT 10;

-- Based on the results from the last query, what 3 crimes are most frequent in the zip code with the highest count of crimes and what is their volume?

SELECT CRIME.OFFENSE_CLASSIFICATION, COUNT(*)
FROM CRIME
INNER JOIN LOCATION ON CRIME.OBJECT_ID = LOCATION.OBJECT_ID
WHERE LOCATION.ZIP_CODE = 40211
GROUP BY CRIME.OFFENSE_CLASSIFICATION
ORDER BY COUNT(*) DESC
LIMIT 3;

-- What are the 3 most frequent crimes in the zip code with the highest count of crimes (using a subquery)?

SELECT CRIME.OFFENSE_CLASSIFICATION
FROM CRIME
INNER JOIN LOCATION ON CRIME.OBJECT_ID = LOCATION.OBJECT_ID
WHERE (SELECT LOCATION.ZIP_CODE
FROM CRIME
INNER JOIN LOCATION ON CRIME.OBJECT_ID = LOCATION.OBJECT_ID
GROUP BY LOCATION.ZIP_CODE
ORDER BY COUNT(*) DESC
LIMIT 1) 
GROUP BY CRIME.OFFENSE_CLASSIFICATION
ORDER BY COUNT(*) DESC
LIMIT 3;

-- Create a view Top3_Crimes_40211 that stores the result of the above query, and display the view.

CREATE VIEW Top3_Crimes_40211 AS
SELECT CRIME.OFFENSE_CLASSIFICATION
FROM CRIME
INNER JOIN LOCATION ON CRIME.OBJECT_ID = LOCATION.OBJECT_ID
WHERE (SELECT CRIME.OFFENSE_CLASSIFICATION
FROM CRIME
INNER JOIN LOCATION ON CRIME.OBJECT_ID = LOCATION.OBJECT_ID
WHERE LOCATION.ZIP_CODE = 40211
GROUP BY CRIME.OFFENSE_CLASSIFICATION
ORDER BY COUNT(*) DESC
LIMIT 1) LOCATION.ZIP_CODE = 40211
GROUP BY CRIME.OFFENSE_CLASSIFICATION
ORDER BY COUNT(*) DESC
LIMIT 3;

SELECT * FROM Top3_Crimes_40211;

-- What is the volume of crimes completed to crimes and crimes not completed?

SELECT CRIME.WAS_OFFENSE_COMPLETED, COUNT(*)
FROM CRIME
GROUP BY CRIME.WAS_OFFENSE_COMPLETED;

-- What are the offense_classification, date_occurred, badge_id and city for all crimes occurring in Jan 2024 in proper date order?

SELECT CRIME.OFFENSE_CLASSIFICATION, DATE.DATE_OCCURRED, OFFICER.BADGE_ID, LOCATION.CITY
FROM CRIME
INNER JOIN DATE ON CRIME.OBJECT_ID = DATE.OBJECT_ID
INNER JOIN OFFICER ON CRIME.OBJECT_ID = OFFICER.OBJECT_ID
INNER JOIN LOCATION ON CRIME.OBJECT_ID = LOCATION.OBJECT_ID
WHERE DATE.DATE_OCCURRED BETWEEN '2024-01-01' AND '2024-01-31'
ORDER BY DATE.DATE_OCCURRED;

-- What are the badge_ids of the 5 officers who responded to the most crimes in March and the volume of crimes responded to by these officers?

SELECT OFFICER.BADGE_ID, COUNT(*)
FROM CRIME
INNER JOIN OFFICER ON CRIME.OBJECT_ID = OFFICER.OBJECT_ID
INNER JOIN DATE ON CRIME.OBJECT_ID = DATE.OBJECT_ID
WHERE DATE.DATE_OCCURRED BETWEEN '2024-03-01' AND '2024-03-31'
GROUP BY OFFICER.BADGE_ID
ORDER BY COUNT(*) DESC
LIMIT 5;

-- What are the volumes of overall crime for each day in March in date order?

SELECT DATE.DATE_OCCURRED, COUNT(*)
FROM DATE 
WHERE DATE.DATE_OCCURRED BETWEEN '2024-03-01' AND '2024-03-31'
GROUP BY DATE.DATE_OCCURRED
ORDER BY DATE.DATE_OCCURRED;

-- What 5 days have the highest volume of crime in April?

SELECT DATE.DATE_OCCURRED, COUNT(*) AS 'Volume'
FROM DATE 
WHERE DATE.DATE_OCCURRED BETWEEN '2024-04-01' AND '2024-04-30'
GROUP BY DATE.DATE_OCCURRED
ORDER BY COUNT(*) DESC
LIMIT 5;

-- What is average volume of crimes for a day in April (this requires a subquery)?

SELECT AVG(Volume)
FROM (SELECT COUNT(*) AS 'Volume'
FROM DATE 
WHERE DATE.DATE_OCCURRED BETWEEN '2024-04-01' AND '2024-04-30'
GROUP BY DATE.DATE_OCCURRED);

-- Let's answer the same question, but this time using a view.

CREATE VIEW April_Crime_Volume AS
SELECT COUNT(*) AS 'Volume'
FROM DATE 
WHERE DATE.DATE_OCCURRED BETWEEN '2024-04-01' AND '2024-04-30'
GROUP BY DATE.DATE_OCCURRED;

SELECT AVG(Volume) FROM April_Crime_Volume;

-- What is the volume of crime by month in the dataset(this requires strftime() function)?

SELECT COUNT(*) AS 'Volume_by_Month'
FROM DATE 
GROUP BY strftime('%m', DATE.DATE_OCCURRED);

-- What is average volume of crime for a month in 2024 (use a subquery)?

SELECT AVG(Volume_by_Month)
FROM (SELECT COUNT(*) AS 'Volume_by_Month'
FROM DATE 
GROUP BY strftime('%m', DATE.DATE_OCCURRED));

-- What are the 5 busiest days for crime and what is their volume?

SELECT DATE.DATE_OCCURRED, COUNT(*)
FROM DATE 
GROUP BY DATE.DATE_OCCURRED
ORDER BY COUNT(*) DESC
LIMIT 5;

-- What are the 5 least busy days for crime and what is their volume?

SELECT DATE.DATE_OCCURRED, COUNT(*)
FROM DATE 
GROUP BY DATE.DATE_OCCURRED
ORDER BY COUNT(*)
LIMIT 5;

-- What are the volumes of crime per year in the date reported column prior to 2024 in chronological order (I call this time travel volume)?

SELECT strftime('%Y', DATE.DATE_REPORTED) 'Year Reported', COUNT(*) AS 'Time Travel Report Volume'
FROM DATE
WHERE strftime('%Y', DATE.DATE_REPORTED) < '2024'
GROUP BY strftime('%Y', DATE.DATE_REPORTED)
ORDER BY strftime('%Y', DATE.DATE_REPORTED);

-- What crimes occurred in what volumes in the zip_code 40241 over the duration of the result set?

SELECT CRIME.OFFENSE_CLASSIFICATION, COUNT(*)
FROM CRIME
INNER JOIN LOCATION ON CRIME.OBJECT_ID = LOCATION.OBJECT_ID
WHERE LOCATION.ZIP_CODE = 40241
GROUP BY CRIME.OFFENSE_CLASSIFICATION
ORDER BY COUNT(*) DESC;

-- What block address had the highest volume of crimes reported in 2024?

SELECT LOCATION.BLOCK_ADDRESS, COUNT(*)
FROM CRIME
INNER JOIN LOCATION ON CRIME.OBJECT_ID = LOCATION.OBJECT_ID
INNER JOIN DATE ON CRIME.OBJECT_ID = DATE.OBJECT_ID
WHERE DATE.DATE_REPORTED >= '2024-01-01'
GROUP BY LOCATION.BLOCK_ADDRESS
ORDER BY COUNT(*) DESC;

-- What block address are crimes reported most frequently in zip_code 40217 and year 2024?

SELECT LOCATION.BLOCK_ADDRESS, COUNT(*)
FROM CRIME
INNER JOIN LOCATION ON CRIME.OBJECT_ID = LOCATION.OBJECT_ID
INNER JOIN DATE ON CRIME.OBJECT_ID = DATE.OBJECT_ID
WHERE LOCATION.ZIP_CODE = 40217 AND DATE.DATE_REPORTED >= '2024-01-01'
GROUP BY LOCATION.BLOCK_ADDRESS
ORDER BY COUNT(*) DESC
LIMIT 1;

-- Which 5 officers most frequently responds to the reports from the above query (Use a subquery)?

SELECT OFFICER.BADGE_ID, COUNT(*)
FROM CRIME
INNER JOIN OFFICER ON CRIME.OBJECT_ID = OFFICER.OBJECT_ID
INNER JOIN LOCATION ON CRIME.OBJECT_ID = LOCATION.OBJECT_ID
WHERE LOCATION.BLOCK_ADDRESS = (SELECT LOCATION.BLOCK_ADDRESS
FROM CRIME
INNER JOIN LOCATION ON CRIME.OBJECT_ID = LOCATION.OBJECT_ID
INNER JOIN DATE ON CRIME.OBJECT_ID = DATE.OBJECT_ID
WHERE LOCATION.ZIP_CODE = 40217 AND DATE.DATE_REPORTED >= '2024-01-01'
GROUP BY LOCATION.BLOCK_ADDRESS
ORDER BY COUNT(*) DESC
LIMIT 1)
GROUP BY OFFICER.BADGE_ID
ORDER BY COUNT(*) DESC
LIMIT 5;

-- What are the Crime (Classification), Badge ID, and volume for all crimes committed between valentines day, and 3/1 in 40204 grouped by crime and badge_id?

SELECT CRIME.OFFENSE_CLASSIFICATION, OFFICER.BADGE_ID, COUNT(*)
FROM CRIME
INNER JOIN OFFICER ON CRIME.OBJECT_ID = OFFICER.OBJECT_ID
INNER JOIN DATE ON CRIME.OBJECT_ID = DATE.OBJECT_ID
INNER JOIN LOCATION ON CRIME.OBJECT_ID = LOCATION.OBJECT_ID
WHERE DATE.DATE_OCCURRED BETWEEN '2024-02-14' AND '2024-03-01' AND LOCATION.ZIP_CODE = 40204
GROUP BY CRIME.OFFENSE_CLASSIFICATION, OFFICER.BADGE_ID
ORDER BY COUNT(*) DESC;

-- What are the most frequent cities and their volumes for crimes not occurring in the city 'Louisville'?

SELECT LOCATION.CITY, COUNT(*)
FROM CRIME 
INNER JOIN LOCATION ON CRIME.OBJECT_ID = LOCATION.OBJECT_ID
WHERE LOCATION.CITY != 'LOUISVILLE'
GROUP BY LOCATION.CITY
ORDER BY COUNT(*) DESC;

-- What are the most frequent crimes and their volumes that have are not completed and have a volume >= 100?

SELECT CRIME.OFFENSE_CLASSIFICATION, COUNT(*)
FROM CRIME
WHERE CRIME.WAS_OFFENSE_COMPLETED = 0
GROUP BY CRIME.OFFENSE_CLASSIFICATION
HAVING COUNT(*) >= 100
ORDER BY COUNT(*) DESC;

-- What are the most frequent crimes and their volumes occurring between 8a and 5p having a volume > 250?

SELECT CRIME.OFFENSE_CLASSIFICATION,  COUNT(*)
FROM CRIME
INNER JOIN DATE ON CRIME.OBJECT_ID = DATE.OBJECT_ID
WHERE strftime('%H', DATE.TIME_OCCURRED) >= '08' AND strftime('%H', DATE.TIME_OCCURRED) < '18'
GROUP BY CRIME.OFFENSE_CLASSIFICATION
HAVING COUNT(*) > 250
ORDER BY COUNT(*) DESC

-- What are the most frequent crimes and their volumes occurring between 8p and 5a having a volume > 500?

SELECT CRIME.OFFENSE_CLASSIFICATION, COUNT(*)
FROM CRIME
INNER JOIN DATE ON CRIME.OBJECT_ID = DATE.OBJECT_ID
WHERE strftime('%H', DATE.TIME_OCCURRED) <= '05' OR strftime('%H', DATE.TIME_OCCURRED) >= '20'
GROUP BY CRIME.OFFENSE_CLASSIFICATION
HAVING COUNT(*) > 500
ORDER BY COUNT(*) DESC

-- What is the most frequent crime and it's volume to occur at 3p that is not '56 ALL OTHER OFFENSES'?

SELECT CRIME.OFFENSE_CLASSIFICATION, COUNT(*)
FROM CRIME
INNER JOIN DATE ON CRIME.OBJECT_ID = DATE.OBJECT_ID
WHERE strftime('%H', DATE.TIME_OCCURRED) = '15' AND CRIME.OFFENSE_CLASSIFICATION != '56 ALL OTHER OFFENSES'
GROUP BY CRIME.OFFENSE_CLASSIFICATION
ORDER BY COUNT(*) DESC
LIMIT 1;

-- What are the volumes by hour in 40223 for the crime '11 SIMPLE ASSAULT' having a volume > 1?

SELECT strftime('%H', DATE.TIME_OCCURRED), COUNT(*)
FROM CRIME
INNER JOIN DATE ON CRIME.OBJECT_ID = DATE.OBJECT_ID
INNER JOIN LOCATION ON CRIME.OBJECT_ID = LOCATION.OBJECT_ID
WHERE CRIME.OFFENSE_CLASSIFICATION = '11 SIMPLE ASSAULT' AND LOCATION.ZIP_CODE = 40223
GROUP BY strftime('%H', DATE.TIME_OCCURRED)
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC;

-- What are the 5 busiest LMPD Divisions by volume?

SELECT OFFICER.LMPD_DIVISION, COUNT(*)
FROM OFFICER
GROUP BY OFFICER.LMPD_DIVISION
ORDER BY COUNT(*) DESC
LIMIT 5;